name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git clone https://WOMANINTECH:$HF_TOKEN@huggingface.co/spaces/WOMANINTECH/Examen-Git-IABD-FOUDA hf-space

          rm -rf hf-space/*

          cp app.py hf-space/ || true
          cp requirements.txt hf-space/ || true
          cp .pre-commit-config.yaml hf-space/ || true
          cp model_weights.pt hf-space/ || true
          cp .gitattributes hf-space/ || true

          cd hf-space

          git add .

          git commit -m "Auto deploy from GitHub Actions" || echo "No changes"

          git push