name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git clone https://WOMANINTECH:$HF_TOKEN@huggingface.co/spaces/WOMANINTECH/Examen-Git-IABD-FOUDA

          cd Examen-Git-IABD-FOUDA

          cp -r ../* .

          git add .

          git commit -m "Auto deploy from GitHub" || echo "No changes"

          git push