name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # Crucial pour que les gros fichiers .pt soient suivis par LFS aussi sur les serveurs de GitHub

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Configuration de l'identité Git temporaire de l'Action
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 2. Ajout du dépôt distant Hugging Face avec le Token secret de manière sécurisée
          # REMPLACE BIEN "VOTRE_USERNAME" et "VOTRE_SPACE_NAME" par tes vraies infos !
          git remote add hf https://x:$HF_TOKEN@huggingface.co/spaces/VOTRE_USERNAME/VOTRE_SPACE_NAME
          
          # 3. Forcer le push du code local vers la branche principale de Hugging Face
          git push --force hf main